# Use the official ASP.NET Core runtime as a base image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 8080

# Set the ASP.NET Core URLS environment variable to use port 8080
ENV ASPNETCORE_URLS=http://+:8080

# Set the entry point for the application
ENTRYPOINT ["dotnet", "MediaPlayer.dll"]